name:                verda
version:             0.1.0.0
github:              "erintorno/verda"
license:             BSD3
author:              "Erin Torno"
maintainer:          "erintorno@gmail.com"
copyright:           "2021 Erin Torno"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erintorno/verda#readme>

dependencies:
- base             >= 4.7 && < 5
- apecs            ^>=0.9
- bytestring       ^>=0.10
- containers       ^>=0.6
- data-default     ^>=0.7
- exceptions       ^>=0.10
- filepath         ^>=1.4
- hashable         ^>=1.3
- hashtables       ^>=1.2
- linear           ^>=1.21
- managed          ^>=1.0
- mtl              ^>=2.2
- primitive        ^>=0.7
- say              ^>=0.1
- sdl2             ^>=2.5
- sdl2-image       ^>=2.0
- text             ^>=1.2.4
- text-manipulate  ^>=0.3
- template-haskell ^>=2.16
- vector           ^>=0.12
- vector-th-unbox  ^>=0.2
- vulkan           ^>=3.11
- vulkan-utils     ^>=0.5.1

ghc-options:
- -Wall
- -Werror
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Wincomplete-uni-patterns

# flags:
#   no-dhall:
#     description: Do not depend on `dhall` or include dhall instances
#     default:     false
#     manual:      true

library:
  source-dirs: src
  dependencies:
  - dhall    ^>=1.39
  - fsnotify ^>=0.3
  # when:
  # - condition: flag(no-dhall)
  #   then:
  #     cpp-options: -Dnodhall
  #   else:
  #     dependencies:
  #     - dhall ^>=1.39

executables:
  examples-shmup:
    main:                Main.hs
    source-dirs:         examples/shmup
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-mconsole
    - -optl-mwindows
    dependencies:
    - verda

tests:
  verda-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-mconsole
    - -optl-mwindows
    dependencies:
    - verda
    - dhall            ^>=1.39
    - directory        ^>=1.3.6
    - hspec            ^>=2.7.8
    - HUnit            ^>=1.6

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- ExplicitForAll
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators